#!/usr/bin/env python3
"""Generate the COLUMN-SENSITIVE examples, rather than hand-spacing them.

The CSD decks in ``examples/`` are free-form and are written by hand. The macro table deck
is not: HLASM continues a statement only when column 72 - column 72 exactly - is non-blank,
and a mark that lands in column 74 continues nothing. That failure is silent. The statement
ends, the next line is read as a fresh one, its operation is not a known macro, and every
operand on it disappears without a word.

This repository's own first draft of ``legacy.pct`` had exactly that bug, which is why the
deck is generated and why ``test_examples.py`` fails if the committed file drifts from what
this produces. Fixtures for a column language are worthless if the columns are approximate,
and hand-spacing does not survive editing.

    python tools/make_examples.py            # rewrite the generated examples
    python tools/make_examples.py --check    # fail if the committed files have drifted
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List, Sequence

REPO = Path(__file__).resolve().parents[1]
EXAMPLES = REPO / "examples"

CONTINUE_COLUMN = 72        # 1-based: the mark goes here and nowhere else
RESUME_COLUMN = 16          # 1-based: a continuation's operands resume here


def statement(label: str, operation: str, operands: Sequence[str]) -> List[str]:
    """One macro statement, continued at column 72 and resumed at column 16.

    Operands are packed greedily, and the continuation mark is placed by measurement
    rather than by counting spaces in a text editor.
    """
    head = "{0:<9}{1} ".format(label, operation)
    lines: List[str] = []
    current = head
    for index, operand in enumerate(operands):
        piece = operand + ("," if index < len(operands) - 1 else "")
        if len(current) + len(piece) > CONTINUE_COLUMN - 1:
            lines.append(current.rstrip().ljust(CONTINUE_COLUMN - 1) + "X")
            current = " " * (RESUME_COLUMN - 1)
        current += piece
    lines.append(current.rstrip())
    return lines


#: (label, operation, operands). A label is blank for a continuation-free body statement.
_LEGACY_PCT = [
    ("DFHPCTL1", "DFHPCT", ["TYPE=INITIAL", "SUFFIX=L1"]),
    ("", "DFHPCT", ["TYPE=ENTRY", "TRANSID=LGMN", "PROGRAM=LGMENU", "TWASIZE=100",
                    "TASKREQ=PF1", "RSLKEY=1"]),
    ("", "DFHPCT", ["TYPE=ENTRY", "TRANSID=LGOR", "PROGRAM=LGORDER", "TWASIZE=512"]),
    ("", "DFHPCT", ["TYPE=FINAL"]),
    ("", "END", []),
    ("DFHPPTL1", "DFHPPT", ["TYPE=INITIAL", "SUFFIX=L1"]),
    ("", "DFHPPT", ["TYPE=ENTRY", "PROGRAM=LGMENU", "PGMLANG=COBOL", "RES=NO"]),
    ("", "DFHPPT", ["TYPE=ENTRY", "PROGRAM=LGORDER", "PGMLANG=COBOL", "RES=NO"]),
    ("", "DFHPPT", ["TYPE=ENTRY", "MAPSET=LGMAP", "RES=YES"]),
    ("", "DFHPPT", ["TYPE=FINAL"]),
    ("", "END", []),
    ("DFHFCTL1", "DFHFCT", ["TYPE=INITIAL", "SUFFIX=L1"]),
    ("", "DFHFCT", ["TYPE=DATASET", "DATASET=CUSTMAS", "ACCMETH=(VSAM,KSDS)",
                    "SERVREQ=(GET,PUT,UPDATE,BROWSE)", "LSRPOOL=1"]),
    ("", "DFHFCT", ["TYPE=DATASET", "DATASET=RATETAB", "ACCMETH=(VSAM,KSDS)",
                    "SERVREQ=(GET,BROWSE)", "LSRPOOL=1"]),
    ("", "DFHFCT", ["TYPE=FINAL"]),
    ("", "END", []),
    ("DFHDCTL1", "DFHDCT", ["TYPE=INITIAL", "SUFFIX=L1"]),
    ("", "DFHDCT", ["TYPE=INTRA", "DESTID=ORDQ", "TRANSID=LGOR", "TRIGLEV=1",
                    "RSL=PUBLIC"]),
    ("", "DFHDCT", ["TYPE=EXTRA", "DESTID=RPTQ", "DSCNAME=LGRPT"]),
    ("", "DFHDCT", ["TYPE=FINAL"]),
    ("", "END", []),
    ("DFHRCTL1", "DSNCRCT", ["TYPE=INIT", "SUFFIX=L1"]),
    ("", "DSNCRCT", ["TYPE=ENTRY", "TXID=LGOR", "PLAN=LGPLAN", "THRDA=2", "THRDM=4"]),
    ("", "DSNCRCT", ["TYPE=FINAL"]),
    ("", "END", []),
]

_LEGACY_PCT_HEADER = """\
*** LEGACY macro table decks - PCT, PPT, FCT, DCT and RCT in one member.
***
*** GENERATED by tools/make_examples.py. Do not hand-edit: HLASM continues a statement
*** only when column 72 - column 72 EXACTLY - is non-blank, and the first draft of this
*** file had its continuation mark in column 74, which continues nothing and loses every
*** operand on the next line without a word.
***
*** WRITTEN FROM IBM'S MACRO DOCUMENTATION, not from a real estate. There is no public
*** corpus of DFHPCT/DFHFCT decks - they survive only inside private estates - so unlike
*** the CSD path, which has AWS CardDemo behind it, this proves only that the code does
*** what it was built to do.
***
*** Note what is NOT here: a GROUP, and a LIST. A macro table has neither. What makes it
*** live is the SIT naming its suffix - PCT=L1 loads DFHPCTL1 - so these resources cannot
*** take part in the GRPLIST closure at all.
"""

_BMS_HEADER = """\
*** LGMAP - a BMS mapset. GENERATED by tools/make_examples.py, for the column reason
*** above. The symbolic map DFHMSD TYPE=DSECT generates from this is what a COBOL program
*** copies: field CUSTNO becomes CUSTNOL, CUSTNOF, CUSTNOA, CUSTNOI and CUSTNOO.
"""

_LGMAP_BMS = [
    ("LGMAP", "DFHMSD", ["TYPE=MAP", "MODE=INOUT", "LANG=COBOL", "STORAGE=AUTO",
                         "TIOAPFX=YES", "CTRL=(FREEKB,FRSET)"]),
    ("LGMENU", "DFHMDI", ["SIZE=(24,80)", "LINE=1", "COLUMN=1"]),
    ("TITLE", "DFHMDF", ["POS=(1,1)", "LENGTH=20", "ATTRB=(PROT,BRT)",
                         "INITIAL='CUSTOMER ORDER ENTRY'"]),
    ("CUSTNO", "DFHMDF", ["POS=(3,1)", "LENGTH=8", "ATTRB=(UNPROT,IC)",
                          "PICIN='X(8)'", "PICOUT='X(8)'"]),
    ("CUSTNM", "DFHMDF", ["POS=(4,1)", "LENGTH=30", "ATTRB=(PROT,NORM)"]),
    ("ORDQTY", "DFHMDF", ["POS=(5,1)", "LENGTH=5", "ATTRB=(UNPROT,NUM)",
                          "PICIN='9(5)'", "PICOUT='ZZZZ9'"]),
    ("MSGOUT", "DFHMDF", ["POS=(23,1)", "LENGTH=79", "ATTRB=(PROT,BRT)"]),
    ("", "DFHMSD", ["TYPE=FINAL"]),
    ("", "END", []),
]


def _render(header: str, statements) -> str:
    lines = [header.rstrip("\n")]
    for label, operation, operands in statements:
        if not operands:
            lines.append("{0:<9}{1}".format(label, operation).rstrip())
            continue
        lines.extend(statement(label, operation, operands))
    return "\n".join(lines) + "\n"


GENERATED = {
    "legacy.pct": lambda: _render(_LEGACY_PCT_HEADER, _LEGACY_PCT),
    "lgmap.bms": lambda: _render(_BMS_HEADER, _LGMAP_BMS),
}


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="fail if a committed example has drifted from the generator")
    args = parser.parse_args(argv)

    drifted = []
    for name, build in sorted(GENERATED.items()):
        path = EXAMPLES / name
        text = build()
        if args.check:
            current = path.read_text(encoding="utf-8") if path.is_file() else None
            if current != text:
                drifted.append(name)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        print("wrote %s (%d lines)" % (path, text.count("\n")))

    if args.check:
        if drifted:
            print("GENERATED EXAMPLES HAVE DRIFTED: %s" % ", ".join(drifted))
            print("\n  python tools/make_examples.py")
            return 1
        print("generated examples match: %s" % ", ".join(sorted(GENERATED)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
